### ISSUE TITLE
Material UI V1 is out - breaking changes

### ISSUE THREAD

**Issue by charliedotau** [Giners/mui-places-autocomplete#38]
Hey @Giners 

It's just come to my attention that Material-UI Version 1 is finally out, and there are some breaking changes

Consequently I'm getting a compilation error, in my app that's now using MUI V1:
`Module not found: Can't resolve 'material-ui/Menu' in '/..../node_modules/mui-places-autocomplete/dist`

so instead of: `import { MenuList, MenuItem } from 'material-ui/Menu'`
you need: `import { MenuList, MenuItem } from '@material-ui/core/Menu'`

**Comment by Giners** [comment]
Hey @charliedotau,

Thanks for filing this. Life has been overwhelmingly busy lately that I had no idea that v1 was finally out. 😄 

I'm trying to carve out sometime to make it a priority to get this fixed now. I'm fairly certain we will rev the major version of our package as a result of this. I see also as part of the breaking changes that React 16.3 or greater is now a must as well.

I'll try to get this fixed ASAP. I've updated the import paths and the `<MUIPlacesAutocomplete>` component appears to work but there are other issues in the demos after updating the import paths. I haven't upgraded to React 16.3 in this project yet so hopefully that will take care of the issues.

**Comment by Giners** [comment]
Hey @charliedotau and @charlax

The issue should be fixed. Let me know if upgrading to v2.0.0 of `<MUIPlacesAutocomplete>` works. I'm sure you're aware since you filed the bugs but you also need to be running React at v16.3.0 or greater.

**Comment by charlax** [comment]
Seems to be working - thanks a lot for the fix!

**Comment by Giners** [comment]
You bet. Happy to help. :smile:

**Comment by charliedotau** [comment]
thanks @Giners.   Working very nicely with MUI-V1.  Love ya work.
thanks
Charlie

**Comment by Giners** [comment]
Thanks @charliedotau. :smile: Promise I will try to get to the other issues once life calms down a bit. Thought it was important to get this working and unblock you and others so I woke up early to get this fixed.
